#!/bin/sh
set -eu

cat > /app/public/runtime-config.js <<EOF
window.__GEODUELS_CONFIG__ = {
  NEXT_PUBLIC_QUEUE_URL: "${NEXT_PUBLIC_QUEUE_URL:-http://localhost:8090}",
  NEXT_PUBLIC_REALTIME_URL: "${NEXT_PUBLIC_REALTIME_URL:-http://localhost:8092}",
  NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL:-}",
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: "${NEXT_PUBLIC_GOOGLE_CLIENT_ID:-}",
  NEXT_PUBLIC_GOOGLE_ALLOWED_ORIGINS: "${NEXT_PUBLIC_GOOGLE_ALLOWED_ORIGINS:-}",
  NEXT_PUBLIC_DISCORD_CLIENT_ID: "${NEXT_PUBLIC_DISCORD_CLIENT_ID:-}",
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: "${NEXT_PUBLIC_TURNSTILE_SITE_KEY:-}",
  NEXT_PUBLIC_GOOGLE_EMBED_KEY: "${NEXT_PUBLIC_GOOGLE_EMBED_KEY:-NO_KEY_DEFINED}",
  NEXT_PUBLIC_APP_VERSION: "${NEXT_PUBLIC_APP_VERSION:-${NEXT_PUBLIC_GIT_SHA:-dev}}"
};
EOF

exec "$@"
