// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leases.sql

package controlplanequeries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireLease = `-- name: AcquireLease :one
insert into control_plane_leases (name, owner_id, fencing_token, expires_at)
values ($1, $2, 1, now() + $3::interval)
on conflict (name) do update
set owner_id = excluded.owner_id,
    fencing_token = case
      when control_plane_leases.owner_id = excluded.owner_id then control_plane_leases.fencing_token
      else control_plane_leases.fencing_token + 1
    end,
    expires_at = excluded.expires_at,
    updated_at = now()
where control_plane_leases.expires_at <= now()
   or control_plane_leases.owner_id = excluded.owner_id
returning fencing_token, expires_at
`

type AcquireLeaseParams struct {
	Name    string          `json:"name"`
	OwnerID string          `json:"owner_id"`
	Column3 pgtype.Interval `json:"column_3"`
}

type AcquireLeaseRow struct {
	FencingToken int64              `json:"fencing_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) AcquireLease(ctx context.Context, arg AcquireLeaseParams) (AcquireLeaseRow, error) {
	row := q.db.QueryRow(ctx, acquireLease, arg.Name, arg.OwnerID, arg.Column3)
	var i AcquireLeaseRow
	err := row.Scan(&i.FencingToken, &i.ExpiresAt)
	return i, err
}

const releaseLease = `-- name: ReleaseLease :exec
delete from control_plane_leases
where name = $1 and owner_id = $2 and fencing_token = $3
`

type ReleaseLeaseParams struct {
	Name         string `json:"name"`
	OwnerID      string `json:"owner_id"`
	FencingToken int64  `json:"fencing_token"`
}

func (q *Queries) ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) error {
	_, err := q.db.Exec(ctx, releaseLease, arg.Name, arg.OwnerID, arg.FencingToken)
	return err
}

const renewLease = `-- name: RenewLease :one
update control_plane_leases
set expires_at = now() + $4::interval,
    updated_at = now()
where name = $1
  and owner_id = $2
  and fencing_token = $3
  and expires_at > now()
returning expires_at
`

type RenewLeaseParams struct {
	Name         string          `json:"name"`
	OwnerID      string          `json:"owner_id"`
	FencingToken int64           `json:"fencing_token"`
	Column4      pgtype.Interval `json:"column_4"`
}

func (q *Queries) RenewLease(ctx context.Context, arg RenewLeaseParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, renewLease,
		arg.Name,
		arg.OwnerID,
		arg.FencingToken,
		arg.Column4,
	)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}
