// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package controlplanequeries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ControlPlaneLease struct {
	Name         string             `json:"name"`
	OwnerID      string             `json:"owner_id"`
	FencingToken int64              `json:"fencing_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
