// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package controlplanequeries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireLease(ctx context.Context, arg AcquireLeaseParams) (AcquireLeaseRow, error)
	ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) error
	RenewLease(ctx context.Context, arg RenewLeaseParams) (pgtype.Timestamptz, error)
}

var _ Querier = (*Queries)(nil)
