-- name: GetMap :one
SELECT m.id::text, coalesce((select a.alias from map_aliases a where a.map_id=m.id order by a.created_at,a.alias limit 1),m.id::text), coalesce(m.owner_user_id::text,''), case when m.official_at is not null then 'GeoDuels' else coalesce(u.display_name,'GeoDuels') end, m.display_name,m.description,m.visibility,m.status,m.difficulty,m.thumbnail_variant,coalesce(m.thumbnail_key,'generic/variant-'||greatest(1,least(5,m.thumbnail_variant))::text),m.location_count,(m.owner_user_id is null or m.official_at is not null),m.official_at is not null,coalesce(m.published_at,'0001-01-01'::timestamptz),m.play_count,m.favorite_count,m.comment_count,m.trending_score,exists(select 1 from map_favorites mf where mf.map_id=m.id and mf.user_id=nullif($1,'')::uuid),trim(both ':' from concat_ws(':',nullif(m.official_region_type,''),nullif(m.official_region_code,''))),exists(select 1 from map_aliases a where a.map_id=m.id and a.alias=coalesce((select value_json->>'movingMapId' from site_settings where key='gameplay_map_settings'),'moving')),exists(select 1 from map_aliases a where a.map_id=m.id and a.alias=coalesce((select value_json->>'noMoveMapId' from site_settings where key='gameplay_map_settings'),'nmpz')),exists(select 1 from map_aliases a where a.map_id=m.id and a.alias=coalesce((select value_json->>'nmpzMapId' from site_settings where key='gameplay_map_settings'),'nmpz')),m.created_at,m.updated_at,pb.best_score,coalesce(pb.match_id::text,''),pb.achieved_at FROM maps m LEFT JOIN users u ON u.id=m.owner_user_id LEFT JOIN player_map_bests pb ON pb.map_id=m.id AND pb.user_id=nullif($1,'')::uuid AND pb.ruleset=0 WHERE (m.id::text=$2 OR exists(select 1 from map_aliases a where a.map_id=m.id AND a.alias=$2)) AND m.archived_at is null AND (m.owner_user_id is null OR m.official_at is not null OR m.owner_user_id=nullif($1,'')::uuid OR m.visibility in ('public','unlisted'));

-- name: ListMaps :many
SELECT m.id::text, coalesce((select a.alias from map_aliases a where a.map_id=m.id order by a.created_at,a.alias limit 1),m.id::text), coalesce(m.owner_user_id::text,''), case when m.official_at is not null then 'GeoDuels' else coalesce(u.display_name,'GeoDuels') end, m.display_name,m.description,m.visibility,m.status,m.difficulty,m.thumbnail_variant,coalesce(m.thumbnail_key,'generic/variant-'||greatest(1,least(5,m.thumbnail_variant))::text),m.location_count,(m.owner_user_id is null or m.official_at is not null),m.official_at is not null,coalesce(m.published_at,'0001-01-01'::timestamptz),m.play_count,m.favorite_count,m.comment_count,m.trending_score,exists(select 1 from map_favorites mf where mf.map_id=m.id and mf.user_id=nullif($1,'')::uuid),trim(both ':' from concat_ws(':',nullif(m.official_region_type,''),nullif(m.official_region_code,''))),exists(select 1 from map_aliases a where a.map_id=m.id and a.alias=coalesce((select value_json->>'movingMapId' from site_settings where key='gameplay_map_settings'),'moving')),exists(select 1 from map_aliases a where a.map_id=m.id and a.alias=coalesce((select value_json->>'noMoveMapId' from site_settings where key='gameplay_map_settings'),'nmpz')),exists(select 1 from map_aliases a where a.map_id=m.id and a.alias=coalesce((select value_json->>'nmpzMapId' from site_settings where key='gameplay_map_settings'),'nmpz')),m.created_at,m.updated_at,pb.best_score,coalesce(pb.match_id::text,''),pb.achieved_at
FROM maps m LEFT JOIN users u ON u.id=m.owner_user_id LEFT JOIN player_map_bests pb ON pb.map_id=m.id AND pb.user_id=nullif($1,'')::uuid AND pb.ruleset=0
WHERE m.archived_at is null AND ($2='all' OR ($2='official' AND (m.owner_user_id is null OR m.official_at is not null)) OR ($2='community' AND m.owner_user_id is not null AND m.visibility='public' AND m.status='ready') OR ($2='favorites' AND exists(select 1 from map_favorites mf where mf.map_id=m.id and mf.user_id=nullif($1,'')::uuid)) OR ($2='mine' AND m.owner_user_id=nullif($1,'')::uuid))
AND ($3='' OR m.display_name ilike $3 escape '\\' OR m.description ilike $3 escape '\\' OR exists(select 1 from map_aliases a where a.map_id=m.id and a.alias ilike $3 escape '\\') OR coalesce(u.display_name,'GeoDuels') ilike $3 escape '\\')
ORDER BY CASE WHEN $4='popular' THEN (m.play_count+m.favorite_count*3) END DESC, CASE WHEN $4='new' THEN m.published_at END DESC NULLS LAST, m.trending_score DESC, m.published_at DESC NULLS LAST, m.updated_at DESC LIMIT 72;
